- hosts: all
  become: yes

  vars:
    pretasks:
      node_hostname: "{{ node_hostname }}"
    docker:
      doc_user: "{{ doc_user }}"
    rancher:
      node_run_cmd: "{{node_run_cmd}}"

  roles:
    - pretasks
    - docker
    - rancher
  